### ISSUE TITLE
增加達明手臂程式

### ISSUE THREAD

**Issue by ziteh** [nfu-irs-lab/robotic-arm-sdk#17]
### 描述
如題

### 備註
--

**Comment by nfurobotlab-member** [comment]
取得位置
傳送：`$TMSCT,47,1,ListenSend(90,GetString(Robot[0].CoordRobot)),*71`
回傳：`$TMSTA,64,90,{518.9999,-122.0011,458.0012,-175.0002,0.0002552914,90.00018},*74`
